### ISSUE TITLE
Bookmarks in merged pdf don't have a destination

### ISSUE THREAD

**Issue by edi-w** [claird/PyPDF4#87]
When merging pdf files, the bookmarks from sourcefiles are inherited correctly but they don't point to any page. Also bookmarks that are created while appending files to the merger don't have a destination. I'm using python 3.7.6.

Example:
`merger = PdfFileMerger()` 
`merger.append(PdfFileReader(filepath,'rb'),bookmark='test',pages=None,import_bookmarks=True)`
`merger.write(open(outfile, 'wb'))`

**Comment by pubpub-zz** [comment]
Hi,
I'm currently preparing a new version in a fork. It seems to work for me

Can you give me your feed back with my proposed version ?(not yet released but attached in here)

[pypdf4-1.27.0PPzz_1-py2.py3-none-any.whl.zip](https://github.com/claird/PyPDF4/files/5052390/pypdf4-1.27.0PPzz_1-py2.py3-none-any.whl.zip)

thanks,

**Comment by edi-w** [comment]
Hi,

I tried that but get this:

    merger.append(filepath)
  File "C:\Users\*\AppData\Local\Programs\Python\Python37\lib\site-packages\pypdf\merger.py", line 146, in append
    self.merge(None, fileobj, bookmark, pages, import_bookmarks)
  File "C:\Users\*\AppData\Local\Programs\Python\Python37\lib\site-packages\pypdf\merger.py", line 116, in merge
    self._copy_bookmarks(fileobj.root_object["/Outlines"], bkmark, srcpages)
  File "C:\Users\*\AppData\Local\Programs\Python\Python37\lib\site-packages\pypdf\merger.py", line 171, in _copy_bookmarks
    self._copy_bookmarks(cur_, bkmark1, srcpages)
  File "C:\Users\*\AppData\Local\Programs\Python\Python37\lib\site-packages\pypdf\merger.py", line 171, in _copy_bookmarks
    self._copy_bookmarks(cur_, bkmark1, srcpages)
  File "C:\Users\*\AppData\Local\Programs\Python\Python37\lib\site-packages\pypdf\merger.py", line 171, in _copy_bookmarks
    self._copy_bookmarks(cur_, bkmark1, srcpages)
  File "C:\Users\*\AppData\Local\Programs\Python\Python37\lib\site-packages\pypdf\merger.py", line 160, in _copy_bookmarks
    if Destination("", node).pageref.idnum in srcpages:
  File "C:\Users\*\AppData\Local\Programs\Python\Python37\lib\site-packages\pypdf\generic.py", line 2205, in __init__
    pdf.get_named_destinations()[page_or_dest_or_array].get_dest_array()
UnboundLocalError: local variable 'pdf' referenced before assignment

**Comment by pubpub-zz** [comment]
I've just made a test similar to yours successfully.
Your trouble may be linked with the content of your pdf file. Is it possible to have a copy?
Thks

**Comment by edi-w** [comment]
[file1.pdf](https://github.com/claird/PyPDF4/files/5095032/file1.pdf)
[file2.pdf](https://github.com/claird/PyPDF4/files/5095034/file2.pdf)

Here's example files with blank pages. I get the same error with these.

**Comment by pubpub-zz** [comment]
thanks for the file. The problem was with the outlines. I've been able to fix it. Can you have a try the attached wheel ?

[pypdf4-1.27.0PPzz_1-py2.py3-none-any.whl.zip](https://github.com/claird/PyPDF4/files/5105699/pypdf4-1.27.0PPzz_1-py2.py3-none-any.whl.zip)

**Comment by edi-w** [comment]
Thanks, I tried and it worked as expected with those files. However, if I append the attached file, I get the following error:

Traceback (most recent call last):
  File "pdflistmerge.py", line 13, in <module>
    merger.append(filepath)
  File "C:\Users\*\AppData\Local\Programs\Python\Python37\lib\site-packages\pypdf\merger.py", line 146, in append
    self.merge(None, fileobj, bookmark, pages, import_bookmarks)
  File "C:\Users\*\AppData\Local\Programs\Python\Python37\lib\site-packages\pypdf\merger.py", line 116, in merge
    self._copy_bookmarks(fileobj.root_object["/Outlines"], bkmark, srcpages)
  File "C:\Users\*\AppData\Local\Programs\Python\Python37\lib\site-packages\pypdf\merger.py", line 162, in _copy_bookmarks
    if Destination("", node).pageref.idnum in srcpages:
  File "C:\Users\*\AppData\Local\Programs\Python\Python37\lib\site-packages\pypdf\generic.py", line 2196, in __init__
    pdf = page_or_dest_or_array.rawGet("/Parent").pdf
  File "C:\Users\*\AppData\Local\Programs\Python\Python37\lib\site-packages\pypdf\generic.py", line 409, in rawGet
    return dict.__getitem__(self, key)
KeyError: '/Parent'
[file3.pdf](https://github.com/claird/PyPDF4/files/5107102/file3.pdf)

**Comment by pubpub-zz** [comment]
Hi Edi-w,
I have to appologize, I've seen your problem just after posting the message, that's why I deleted it.
This should work now:
[pypdf4-1.27.0PPzz_1-py2.py3-none-any.whl.zip](https://github.com/claird/PyPDF4/files/5110499/pypdf4-1.27.0PPzz_1-py2.py3-none-any.whl.zip)

**Comment by edi-w** [comment]
Hi,
as far as I can tell, that seems to be working exactly as expected. Thanks!
